version: "3"

services:
  mkdocs:
    container_name: mkdocs
    image: squidfunk/mkdocs-material:latest
    #image: polinux/mkdocs:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      LIVE_RELOAD_SUPPORT: 'true'
      ADD_MODULES: 'fontawesome-markdown mkdocs-git-revision-date-localized-plugin mkdocs-material'
      FAST_MODE: 'true'
      UPDATE_INTERVAL: 15
      AUTO_UPDATE: 'true'
    volumes:
      - '.:/docs'